const http = require("http");
const notifier = require("./notifier.js");
var fs = require("fs");

/**
 * RemindMe Notifications server
 * @description Starts an HTTP server on port 80.
 * 
 * Returns a Promise whose resolution value is the
 * httpServer object.
 * 
 * 
 * =========================== END POINTS =============================
 * 
 * GET /reminder
 * Response status codes
 * 		If succesful: 200
 * 		If incorrect request from client: 400
 * 		If an error occured on the server: 500
 * Response body 
 * 		If succesful: should contain a JSON object of the form, { "reminders" : [ {id, task, type, duration}, ... ] }
 * 		If inccorect request from the client: { message: "Incorrect input" }
 * 		If an error occured on the server: { error: <Error object> }
 * 
 * 
 * POST /reminder
 * Response status codes
 * 		If succesful: 200
 * 		If incorrect request from client: 400
 * 		If an error occured on the server: 500
 * Response body
 * 		If succesful: should contain a JSON object of the form, { "taskId": "Some task identifier generated by the server" }
 * 		If incorrect request from client: { message: "Incorrect input" }
 * 		If an error occured on the server: { error: <Error object> }
 * 
 * 
 * DELETE /reminder: 
 * Response status codes
 * 		If succesfull: 200
 * 		If incorrect request from client: 400
 * 		If an error occured on the server: 500
 * Response body 
 * 		If succesful: should be an empty object, {}
 * 		If incorrect request from client: { message: "Incorrect input" }
 * 		If an error occured on the server: { error: <Error object> }
 * 
 * 
 * ANY OTHER *:
 * Response status code: 404
 * Response body: { "message": "Not Found." }
 * 
 * ====================================================================
 */

const server = http.createServer(req, res => {
	if(res) {
		if(req.method === 'GET' && req.url === '/reminder') { 
			// fetching all reminders
			res.writeHead(200, {'Content-Type': 'application/json'});
			res.write(JSON.stringify({id:'', task:'', type:'', duration:''})); 
			res.end();
		} else if(req.method === 'POST') {
			// creating reminder
			if(req.url === '/reminder' && req.method === 'POST') {
				req.on('data', function(data) {
					reqBody = data;
					res.writeHead();
					res.write(data);
					res.end();
				})
			} 
		} else {
			// for incorrect request
			res.writeHead(400, {'Content-Type': 'text/plain'});
			res.write('client side error occured');
			res.end();
		}
	} else if(!res) {
		// for no response
		res.writeHead(500, {'Content-Type': 'text/plain'});
		res.write('server side error occured');
		res.end();
	} else {
		// for some other error
		res.writeHead(404, {'Content-Type': 'text/plain'});
		res.write('404: not found');
		res.end();
	}
})

const host = 'localhost'
const port = process.env.PORT || 3000;
server.listen(port, host, () => console.log(`Server has started at ${host}/${ port }`));

module.exports = run;